# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'methods_comparison_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 495)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.res_info_layout = QtWidgets.QVBoxLayout()
        self.res_info_layout.setObjectName("res_info_layout")
        self.res_info_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res_info_label.sizePolicy().hasHeightForWidth())
        self.res_info_label.setSizePolicy(sizePolicy)
        self.res_info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.res_info_label.setObjectName("res_info_label")
        self.res_info_layout.addWidget(self.res_info_label)
        self.dynamic_res_info = QtWidgets.QHBoxLayout()
        self.dynamic_res_info.setObjectName("dynamic_res_info")
        self.brute_info = QtWidgets.QVBoxLayout()
        self.brute_info.setObjectName("brute_info")
        self.brute_title_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brute_title_label.sizePolicy().hasHeightForWidth())
        self.brute_title_label.setSizePolicy(sizePolicy)
        self.brute_title_label.setObjectName("brute_title_label")
        self.brute_info.addWidget(self.brute_title_label)
        self.brute_info_browser = QtWidgets.QTextBrowser(self.main_widget)
        self.brute_info_browser.setObjectName("brute_info_browser")
        self.brute_info.addWidget(self.brute_info_browser)
        self.dynamic_res_info.addLayout(self.brute_info)
        self.bellman_info = QtWidgets.QVBoxLayout()
        self.bellman_info.setObjectName("bellman_info")
        self.bellamn_title_label = QtWidgets.QLabel(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bellamn_title_label.sizePolicy().hasHeightForWidth())
        self.bellamn_title_label.setSizePolicy(sizePolicy)
        self.bellamn_title_label.setObjectName("bellamn_title_label")
        self.bellman_info.addWidget(self.bellamn_title_label)
        self.bellman_info_browser = QtWidgets.QTextBrowser(self.main_widget)
        self.bellman_info_browser.setObjectName("bellman_info_browser")
        self.bellman_info.addWidget(self.bellman_info_browser)
        self.dynamic_res_info.addLayout(self.bellman_info)
        self.res_info_layout.addLayout(self.dynamic_res_info)
        self.horizontalLayout_2.addLayout(self.res_info_layout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.controlbar_groupbox = QtWidgets.QGroupBox(self.main_widget)
        self.controlbar_groupbox.setObjectName("controlbar_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlbar_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_type_groupbox = QtWidgets.QGroupBox(self.controlbar_groupbox)
        self.input_type_groupbox.setObjectName("input_type_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.input_type_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_file = QtWidgets.QRadioButton(self.input_type_groupbox)
        self.radio_file.setChecked(True)
        self.radio_file.setObjectName("radio_file")
        self.horizontalLayout.addWidget(self.radio_file)
        self.radio_keyboard = QtWidgets.QRadioButton(self.input_type_groupbox)
        self.radio_keyboard.setChecked(False)
        self.radio_keyboard.setObjectName("radio_keyboard")
        self.horizontalLayout.addWidget(self.radio_keyboard)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.input_button = QtWidgets.QPushButton(self.input_type_groupbox)
        self.input_button.setObjectName("input_button")
        self.verticalLayout_3.addWidget(self.input_button)
        self.verticalLayout.addWidget(self.input_type_groupbox)
        self.control_bar = QtWidgets.QVBoxLayout()
        self.control_bar.setObjectName("control_bar")
        self.first_city_label = QtWidgets.QLabel(self.controlbar_groupbox)
        self.first_city_label.setObjectName("first_city_label")
        self.control_bar.addWidget(self.first_city_label)
        self.first_city_spin_box = QtWidgets.QSpinBox(self.controlbar_groupbox)
        self.first_city_spin_box.setMinimum(1)
        self.first_city_spin_box.setMaximum(1)
        self.first_city_spin_box.setObjectName("first_city_spin_box")
        self.control_bar.addWidget(self.first_city_spin_box)
        self.task_type_groupbox = QtWidgets.QGroupBox(self.controlbar_groupbox)
        self.task_type_groupbox.setObjectName("task_type_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.task_type_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.min_type_radio = QtWidgets.QRadioButton(self.task_type_groupbox)
        self.min_type_radio.setChecked(True)
        self.min_type_radio.setObjectName("min_type_radio")
        self.horizontalLayout_3.addWidget(self.min_type_radio)
        self.max_type_radio = QtWidgets.QRadioButton(self.task_type_groupbox)
        self.max_type_radio.setChecked(False)
        self.max_type_radio.setObjectName("max_type_radio")
        self.horizontalLayout_3.addWidget(self.max_type_radio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.control_bar.addWidget(self.task_type_groupbox)
        self.pushButton = QtWidgets.QPushButton(self.controlbar_groupbox)
        self.pushButton.setObjectName("pushButton")
        self.control_bar.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.control_bar)
        self.verticalLayout_2.addWidget(self.controlbar_groupbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.res_info_label.setText(_translate("MainWindow", "Results:"))
        self.brute_title_label.setText(_translate("MainWindow", "Brute force:"))
        self.bellamn_title_label.setText(_translate("MainWindow", "Dynamic programming:"))
        self.controlbar_groupbox.setTitle(_translate("MainWindow", "Control panel"))
        self.input_type_groupbox.setTitle(_translate("MainWindow", "Choose data input type"))
        self.radio_file.setText(_translate("MainWindow", "from file"))
        self.radio_keyboard.setText(_translate("MainWindow", "from keyboard"))
        self.input_button.setText(_translate("MainWindow", "Choose file"))
        self.first_city_label.setText(_translate("MainWindow", "Choose first city:"))
        self.task_type_groupbox.setTitle(_translate("MainWindow", "Choose task type:"))
        self.min_type_radio.setText(_translate("MainWindow", "find minimum"))
        self.max_type_radio.setText(_translate("MainWindow", "find maximum"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))

