# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'methods_comparison_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(257, 276)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.input_groupbox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_groupbox.sizePolicy().hasHeightForWidth())
        self.input_groupbox.setSizePolicy(sizePolicy)
        self.input_groupbox.setObjectName("input_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.input_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dimension_groupbox = QtWidgets.QGroupBox(self.input_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dimension_groupbox.sizePolicy().hasHeightForWidth())
        self.dimension_groupbox.setSizePolicy(sizePolicy)
        self.dimension_groupbox.setObjectName("dimension_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dimension_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dimension_spinbox = QtWidgets.QSpinBox(self.dimension_groupbox)
        self.dimension_spinbox.setMinimum(3)
        self.dimension_spinbox.setMaximum(50)
        self.dimension_spinbox.setObjectName("dimension_spinbox")
        self.verticalLayout.addWidget(self.dimension_spinbox)
        self.dimension_slider = QtWidgets.QSlider(self.dimension_groupbox)
        self.dimension_slider.setMinimum(3)
        self.dimension_slider.setMaximum(50)
        self.dimension_slider.setSliderPosition(3)
        self.dimension_slider.setOrientation(QtCore.Qt.Horizontal)
        self.dimension_slider.setObjectName("dimension_slider")
        self.verticalLayout.addWidget(self.dimension_slider)
        self.verticalLayout_2.addWidget(self.dimension_groupbox)
        self.matr_layout = QtWidgets.QGridLayout()
        self.matr_layout.setSpacing(3)
        self.matr_layout.setObjectName("matr_layout")
        self.matr_2 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_2.setObjectName("matr_2")
        self.matr_layout.addWidget(self.matr_2, 0, 1, 1, 1)
        self.matr_4 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_4.setObjectName("matr_4")
        self.matr_layout.addWidget(self.matr_4, 3, 0, 1, 1)
        self.matr_7 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_7.setObjectName("matr_7")
        self.matr_layout.addWidget(self.matr_7, 6, 0, 1, 1)
        self.matr_1 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_1.setObjectName("matr_1")
        self.matr_layout.addWidget(self.matr_1, 0, 0, 1, 1)
        self.matr_3 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_3.setObjectName("matr_3")
        self.matr_layout.addWidget(self.matr_3, 0, 2, 1, 1)
        self.matr_5 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_5.setObjectName("matr_5")
        self.matr_layout.addWidget(self.matr_5, 3, 1, 1, 1)
        self.matr_6 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_6.setObjectName("matr_6")
        self.matr_layout.addWidget(self.matr_6, 3, 2, 1, 1)
        self.matr_8 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        self.matr_8.setObjectName("matr_8")
        self.matr_layout.addWidget(self.matr_8, 6, 1, 1, 1)
        self.matr_9 = QtWidgets.QDoubleSpinBox(self.input_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matr_9.sizePolicy().hasHeightForWidth())
        self.matr_9.setSizePolicy(sizePolicy)
        self.matr_9.setObjectName("matr_9")
        self.matr_layout.addWidget(self.matr_9, 6, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.matr_layout)
        self.verticalLayout_3.addWidget(self.input_groupbox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.input_groupbox.setTitle(_translate("Dialog", "Matrix keyboard input"))
        self.dimension_groupbox.setTitle(_translate("Dialog", "Input matrix dimension"))

